### ISSUE TITLE
http.post 第二次打开显示cannot make a new requests

### ISSUE THREAD

**Issue by fsdsoyu** [kkevsekk1/AutoX#352]
依次执行两次不同url的post，第二个post显示：
00:41:49.944/V: 开始运行[[remote]auto.js]
00:41:50.753/E: Wrapped java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close() (file:///android_asset/modules/__http__.js#49)
Wrapped java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
    at file:///android_asset/modules/__http__.js:49:0
    at getQlist ([remote]auto.js:51:0) ====>自己定义的函数
    at [remote]auto.js:71:0

00:41:50.755/V: 
------------
[[remote]auto.js]运行结束，用时0.809000秒

**Comment by kkevsekk1** [comment]
可能是多线程，单实例造成的，让请求串行化运行，试试，看看结果如何



发送自我的盖乐世



-------- 原始信息 --------
发件人： FsdSoyu ***@***.***>
日期: 2022/7/3 01:11 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] http.post 第二次打开显示cannot make a new requests (Issue #352)


依次执行两次不同url的post，第二个post显示：
00:41:49.944/V: 开始运行[[remote]auto.js]
00:41:50.753/E: Wrapped java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close() (file:///android_asset/modules/http.js#49)
Wrapped java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
at file:///android_asset/modules/http.js:49:0
at getQlist ([remote]auto.js:51:0) ====>自己定义的函数
at [remote]auto.js:71:0

00:41:50.755/V:

[[remote]auto.js]运行结束，用时0.809000秒

―

**Comment by fsdsoyu** [comment]
console.show();
var token = getToken();
var ddd = getQlist(token);
console.info(ddd);

//
两个函数都是定义了url 和 header，然后http.post()后res.body.string()，然后返回json获取信息
就是顺序执行两个post。

**Comment by kkevsekk1** [comment]
这样的代码不应该啊，什么版本……



发送自我的盖乐世



-------- 原始信息 --------
发件人： FsdSoyu ***@***.***>
日期: 2022/7/3 14:59 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] http.post 第二次打开显示cannot make a new requests (Issue #352)


console.show();
var token = getToken();
var ddd = getQlist(token);
console.info(ddd);

//
两个函数都是定义了url 和 header，然后http.post()后res.body.string()，然后返回json获取信息
就是顺序执行两个post。

―

**Comment by fsdsoyu** [comment]
[6.1.9](https://github.com/kkevsekk1/AutoX/releases/tag/6.1.9)
我就是个小白，在chrome下用XMLHttpRequest好像没有这个问题

**Comment by kkevsekk1** [comment]
Chrome和这个实现是完全不相同的，你用5.几的试一下看看



发送自我的盖乐世



-------- 原始信息 --------
发件人： FsdSoyu ***@***.***>
日期: 2022/7/3 16:47 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] http.post 第二次打开显示cannot make a new requests (Issue #352)


6.1.9<https://github.com/kkevsekk1/AutoX/releases/tag/6.1.9>
我就是个小白，在chrome下用XMLHttpRequest好像没有这个问题

―

**Comment by falcolee** [comment]
我也遇到这个问题了，重试机制有问题，这里测试修复了，已提pr

**Comment by runtimme** [comment]
version 6.2.4 问题依然存在

**Comment by kkevsekk1** [comment]
已修复
