### ISSUE TITLE
socket.io-client error problem

### ISSUE THREAD

**Issue by frsh18** [kkevsekk1/AutoX#559]
Does socket.io-client have support? Because when I want to use it, there is no way to use it. Lots of errors. There is no way to modify and adjust. Does anyone know the real problem?

**Comment by kkevsekk1** [comment]
有websocket的示例


发送自我的盖乐世



-------- 原始信息 --------
发件人： frsh18 ***@***.***>
日期: 2023/4/30 06:36 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] socket.io-client error problem (Issue #559)


Does socket.io-client have support? Because when I want to use it, there is no way to use it. Lots of errors. There is no way to modify and adjust. Does anyone know the real problem?

―

**Comment by kkevsekk1** [comment]
里面带okhttp的jar，Java能用的，这里都能用



发送自我的盖乐世



-------- 原始信息 --------
发件人： frsh18 ***@***.***>
日期: 2023/4/30 06:36 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] socket.io-client error problem (Issue #559)


Does socket.io-client have support? Because when I want to use it, there is no way to use it. Lots of errors. There is no way to modify and adjust. Does anyone know the real problem?

―

**Comment by vipterry** [comment]
> Does socket.io-client have support? Because when I want to use it, there is no way to use it. Lots of errors. There is no way to modify and adjust. Does anyone know the real problem?

Socket.io is a native WebSocket implementation based on NodeJS or browser, and you need to implement your own simulation layer based on okHTTP. Please refer to the following code snippets:

<img width="741" alt="image" src="https://github.com/kkevsekk1/AutoX/assets/7145196/fee67498-04e2-4940-b75e-960f42a7e271">
<img width="1030" alt="image" src="https://github.com/kkevsekk1/AutoX/assets/7145196/b9d2c21d-a067-4789-8896-9290d4a60cdf">
