### ISSUE TITLE
一天崩溃几次

### ISSUE THREAD

**Issue by hduwhyso** [kkevsekk1/AutoX#710]
Version: 653
Android: 33
kotlin.UninitializedPropertyAccessException: lateinit property mScriptEngine has not been initialized
java.lang.RuntimeException:Unable to destroy activity {org.autojs.autoxjs.v6/com.stardust.autojs.execution.ScriptExecuteActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mScriptEngine has not been initialized
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5688)
......
Caused by:
kotlin.UninitializedPropertyAccessException:lateinit property mScriptEngine has not been initialized
com.stardust.autojs.execution.ScriptExecuteActivity.onDestroy(ScriptExecuteActivity.kt:125)
android.app.Activity.performDestroy(Activity.java:8843)
android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1472)
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5675)
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5721)
android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loopOnce(Looper.java:211)
android.os.Looper.loop(Looper.java:300)
android.app.ActivityThread.main(ActivityThread.java:8315)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by kkevsekk1** [comment]
问题应该还是在代码



发送自我的盖乐世



-------- 原始信息 --------
发件人： Change ***@***.***>
日期: 2023/10/29 18:51 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 一天崩溃几次 (Issue #710)


Version: 653
Android: 33
kotlin.UninitializedPropertyAccessException: lateinit property mScriptEngine has not been initialized
java.lang.RuntimeException:Unable to destroy activity {org.autojs.autoxjs.v6/com.stardust.autojs.execution.ScriptExecuteActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mScriptEngine has not been initialized
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5688)
......
Caused by:
kotlin.UninitializedPropertyAccessException:lateinit property mScriptEngine has not been initialized
com.stardust.autojs.execution.ScriptExecuteActivity.onDestroy(ScriptExecuteActivity.kt:125)
android.app.Activity.performDestroy(Activity.java:8843)
android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1472)
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5675)
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5721)
android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loopOnce(Looper.java:211)
android.os.Looper.loop(Looper.java:300)
android.app.ActivityThread.main(ActivityThread.java:8315)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

―

**Comment by hduwhyso** [comment]
嗯，应该是代码问题。但是我意思，代码有问题能不能是报错，而不是崩溃，不然都不知道哪里问题。代码把软件搞崩溃，软件也得反思

**Comment by aiselp** [comment]
这个报错确实和最近的改动有关系，
通常发生在使用脚本引擎启动ui脚本失败时出现
